# Generated by Django 3.2.7 on 2021-09-02 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=10, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('priority', models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Completed', 'COMPLETED'), ('Inactive', 'INACTIVE')], max_length=10)),
                ('taskId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_name', models.ManyToManyField(blank=True, to='VerilistApp.List')),
            ],
        ),
    ]
