# Generated by Django 3.2.7 on 2021-09-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VerilistApp', '0003_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='list_name',
        ),
        migrations.AddField(
            model_name='task',
            name='list_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='VerilistApp.list'),
        ),
    ]
