# Generated by Django 3.2.7 on 2021-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerilistApp', '0006_alter_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
