# Generated by Django 3.2.7 on 2021-09-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VerilistApp', '0007_alter_list_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='VerilistApp.list'),
        ),
    ]
