# Generated by Django 3.2.7 on 2021-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerilistApp', '0008_alter_task_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
