# Generated by Django 3.2.7 on 2021-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerilistApp', '0010_auto_20210902_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='Verilist Null Task', max_length=50),
        ),
    ]
